version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - BASE_URL=${BASE_URL}
      - REDIS_URI=redis://default:gNYCUUTKnabkWUDJvmUyrb3ozJesP6CK@redis-17596.c240.us-east-1-3.ec2.redns.redis-cloud.com:17596
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

volumes:
  mongo-data: {}